arch:
  - amd64
  - ppc64le
language: go

services:
  - docker

install:
  - A=${PWD#*github.com/};A=${A%/ffjson};cd ../..;mv $A pquerna;cd pquerna/ffjson
  - go get -d -v -t ./...

script: make clean && make lint && make test && make test 

jobs:
  include:
    - stage: Fuzz regression
      go: 1.13.x
      dist: bionic
      script:
        - cd tests/fuzz
        - ./fuzzit.sh local-regression
    - stage: Fuzz
      if: branch = master AND type IN (push)
      go: 1.14.x
      dist: bionic
      script:
        - cd tests/fuzz
        - ./fuzzit.sh fuzzing

go:
  - "1.13.x"
  - "1.14.x"

env:
  GO15VENDOREXPERIMENT=1
